# Generated by Django 2.2.7 on 2019-11-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigbossapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcontestent',
            name='image',
        ),
    ]
