# Generated by Django 2.2.7 on 2019-11-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbossapp', '0002_remove_addcontestent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcontestent',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
