# Generated by Django 2.2.7 on 2019-11-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbossapp', '0003_addcontestent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
