# Generated by Django 2.2.7 on 2019-11-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbossapp', '0005_auto_20191121_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='votingmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
