# Generated by Django 2.2.7 on 2019-11-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbossapp', '0006_votingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingmodel',
            name='contestent_name',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
